// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGyL3d06JFo1QLo-n9XJYNVIaMxqjZ5g',
    appId: '1:50003705419:android:d959a55c75cdf74db617ce',
    messagingSenderId: '50003705419',
    projectId: 'spendsnapx9',
    databaseURL: 'https://spendsnapx9-default-rtdb.firebaseio.com',
    storageBucket: 'spendsnapx9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfW3B-TW8VaO1GyOy_zjLLf4WYt4Wxsnc',
    appId: '1:50003705419:ios:832112ddb90988e2b617ce',
    messagingSenderId: '50003705419',
    projectId: 'spendsnapx9',
    databaseURL: 'https://spendsnapx9-default-rtdb.firebaseio.com',
    storageBucket: 'spendsnapx9.firebasestorage.app',
    iosClientId: '50003705419-equipf2vfo768be2v7b327cvkfcfd191.apps.googleusercontent.com',
    iosBundleId: 'com.ncu.spendsnap',
  );
}
